"""
Expanded 3D LUT (.cube) Generator for Video Auto-Editor Pipeline
Generates 10 industry-standard 17x17x17 3D LUT .cube files:
1. Cinematic Teal & Orange
2. YouTube Vibrant Pop
3. Moody Dark Film
4. Vintage VHS Retro
5. Cyberpunk Neon
6. Sunset Golden Hour
7. Matrix Cyber Green
8. Bleach Bypass Action
9. Pastel Aesthetic Vlog
10. Monochrome Red Spotlight (Selective Color)
"""

import math
import os
import sys

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

def generate_cube_lut(filename, title, transform_func, size=17):
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, 'w') as f:
        f.write(f'# Generated by Video Auto-Editor Pipeline\n')
        f.write(f'TITLE "{title}"\n')
        f.write(f'LUT_3D_SIZE {size}\n')
        f.write(f'DOMAIN_MIN 0.0 0.0 0.0\n')
        f.write(f'DOMAIN_MAX 1.0 1.0 1.0\n\n')
        
        for b_idx in range(size):
            b = b_idx / (size - 1)
            for g_idx in range(size):
                g = g_idx / (size - 1)
                for r_idx in range(size):
                    r = r_idx / (size - 1)
                    ro, go, bo = transform_func(r, g, b)
                    ro = max(0.0, min(1.0, ro))
                    go = max(0.0, min(1.0, go))
                    bo = max(0.0, min(1.0, bo))
                    f.write(f"{ro:.6f} {go:.6f} {bo:.6f}\n")

# 1. Cinematic Teal & Orange
def teal_orange_grade(r, g, b):
    luma = 0.299 * r + 0.587 * g + 0.114 * b
    r_c = r * r * (3.0 - 2.0 * r)
    g_c = g * g * (3.0 - 2.0 * g)
    b_c = b * b * (3.0 - 2.0 * b)
    if luma > 0.4:
        return r_c * 1.15, g_c * 1.02, b_c * 0.85
    else:
        return r_c * 0.82, g_c * 1.05, b_c * 1.25

# 2. YouTube Vibrant Pop
def vibrant_pop_grade(r, g, b):
    luma = 0.299 * r + 0.587 * g + 0.114 * b
    sat = 1.35
    r_sat = max(0.0, luma + (r - luma) * sat)
    g_sat = max(0.0, luma + (g - luma) * sat)
    b_sat = max(0.0, luma + (b - luma) * sat)
    return math.pow(r_sat, 0.92), math.pow(g_sat, 0.92), math.pow(b_sat, 0.92)

# 3. Moody Dark Film
def moody_dark_grade(r, g, b):
    luma = 0.299 * r + 0.587 * g + 0.114 * b
    sat = 0.80
    r_d = max(0.0, luma + (r - luma) * sat)
    g_d = max(0.0, luma + (g - luma) * sat)
    b_d = max(0.0, luma + (b - luma) * sat)
    return math.pow(r_d, 1.18) * 0.95, math.pow(g_d, 1.18) * 0.95, math.pow(b_d, 1.12) * 1.05

# 4. Vintage VHS Retro
def vintage_vhs_grade(r, g, b):
    r_lift = 0.06 + 0.94 * r
    g_lift = 0.05 + 0.94 * g
    b_lift = 0.08 + 0.92 * b
    return r_lift * 1.05, g_lift * 1.08, b_lift * 0.92

# 5. Cyberpunk Neon
def cyberpunk_neon_grade(r, g, b):
    r_out = r * 1.2 if r > g else r * 0.7
    g_out = g * 0.85
    b_out = b * 1.4
    return r_out, g_out, b_out

# 6. Sunset Golden Hour
def sunset_golden_grade(r, g, b):
    luma = 0.299 * r + 0.587 * g + 0.114 * b
    r_out = r * 1.22
    g_out = g * 1.04
    b_out = b * 0.78
    return math.pow(max(0.0, r_out), 0.95), math.pow(max(0.0, g_out), 0.98), math.pow(max(0.0, b_out), 1.05)

# 7. Matrix Cyber Green
def matrix_cyber_grade(r, g, b):
    luma = 0.299 * r + 0.587 * g + 0.114 * b
    r_out = luma * 0.65
    g_out = luma * 1.25 + 0.04
    b_out = luma * 0.70
    return r_out, g_out, b_out

# 8. Bleach Bypass Gritty Action
def bleach_bypass_grade(r, g, b):
    luma = 0.299 * r + 0.587 * g + 0.114 * b
    # High contrast overlay blend with luma
    r_out = 2.0 * r * luma if r < 0.5 else 1.0 - 2.0 * (1.0 - r) * (1.0 - luma)
    g_out = 2.0 * g * luma if g < 0.5 else 1.0 - 2.0 * (1.0 - g) * (1.0 - luma)
    b_out = 2.0 * b * luma if b < 0.5 else 1.0 - 2.0 * (1.0 - b) * (1.0 - luma)
    # Desaturate
    r_fin = luma * 0.4 + r_out * 0.6
    g_fin = luma * 0.4 + g_out * 0.6
    b_fin = luma * 0.4 + b_out * 0.6
    return r_fin, g_fin, b_fin

# 9. Pastel Aesthetic Vlog
def pastel_vlog_grade(r, g, b):
    r_soft = 0.05 + 0.90 * math.pow(r, 0.9)
    g_soft = 0.04 + 0.92 * math.pow(g, 0.9)
    b_soft = 0.06 + 0.90 * math.pow(b, 0.9)
    return r_soft * 1.03, g_soft * 1.01, b_soft * 1.05

# 10. Monochrome Red Spotlight (Selective Color)
def mono_red_spotlight_grade(r, g, b):
    luma = 0.299 * r + 0.587 * g + 0.114 * b
    # Check if color is primarily red
    is_red = (r > 0.35) and (r > g * 1.4) and (r > b * 1.4)
    if is_red:
        return r * 1.15, g * 0.3, b * 0.3
    else:
        return luma, luma, luma

def build_all_luts(output_dir):
    os.makedirs(output_dir, exist_ok=True)
    luts = {
        "cinematic_teal_orange.cube": ("Cinematic Teal & Orange", teal_orange_grade),
        "youtube_vibrant_pop.cube": ("YouTube Vibrant Pop", vibrant_pop_grade),
        "moody_dark_film.cube": ("Moody Dark Film", moody_dark_grade),
        "vintage_vhs_retro.cube": ("Vintage VHS Retro", vintage_vhs_grade),
        "cyberpunk_neon.cube": ("Cyberpunk Neon", cyberpunk_neon_grade),
        "sunset_golden_hour.cube": ("Sunset Golden Hour", sunset_golden_grade),
        "matrix_cyber_green.cube": ("Matrix Cyber Green", matrix_cyber_grade),
        "bleach_bypass_action.cube": ("Bleach Bypass Action", bleach_bypass_grade),
        "pastel_aesthetic_vlog.cube": ("Pastel Aesthetic Vlog", pastel_vlog_grade),
        "monochrome_red_spotlight.cube": ("Monochrome Red Spotlight", mono_red_spotlight_grade)
    }
    
    print(f"Generating {len(luts)} 3D LUT (.cube) files into: {output_dir}")
    for filename, (title, func) in luts.items():
        filepath = os.path.join(output_dir, filename)
        generate_cube_lut(filepath, title, func, size=17)
        print(f"  [OK] Created: {filename}")

if __name__ == "__main__":
    current_dir = os.path.dirname(os.path.abspath(__file__))
    build_all_luts(os.path.join(current_dir, "cube_files"))
